name: vnet_agenda
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2 
  flutter_secure_storage: ^8.0.0
  universal_io: ^2.2.0  # Para detectar la plataforma
  dotenv: ^4.2.0         # Para manejar variables de entorno
  http: ^1.1.0
  logger: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  

flutter:
  assets:
    - assets/images/image001.png
    - assets/images/image002.png
  uses-material-design: true

